server {
    listen 80;

    # /api 경로로 들어오는 요청은 백엔드 컨테이너로 전달
    location /api/ {
        proxy_pass http://backend:8080;   # 도커 내부망 호스트명 사용
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 파일 업로드 요청은 10MB 제한
    location /api/document/upload {
            client_max_body_size 10M; //업로드 요청 10MB 제한
            proxy_pass http://backend:8080;   # 도커 내부망 호스트명 사용
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    # 일반 접속은 React 정적 파일 서빙
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;   # React SPA 라우팅 지원
    }
}