services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: gov_db
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis-cache
    restart: always

  backend:
    build: .
    container_name: spring-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gov_db?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SERVER_FORWARD_HEADERS_STRATEGY: framework
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data: